export enum AppRoute {
  AUTH = "Auth",
  SIGN_IN = "Sign In",
  SIGN_UP = "Sign Up",
  RESET_PASSWORD = "Reset Passrord",
  HOME = "Home",
  TODO = "ToDo",
  TODO_IN_PROGRESS = "ToDo In Progress",
  TODO_DONE = "ToDo Done",
  TODO_DETAILS = "ToDo Details",
  ITEM = "Item",
  ITEM_DETAILS = "Item Details",
  RENTAL_ITEMS = "Rental Items",
  SETTING = "Setting",
  HISTORY_DETAIL = "History Detail",
}
